import type { ReactNode } from "react";
import { CONTACT_EMAIL } from "../lib/studio";

export function SiteNav({ links }: { links?: ReactNode }) {
  return (
    <header className="site-nav">
      <div className="site-nav-inner">
        <a className="wordmark" href="/">
          Orune
        </a>
        <nav aria-label="Site">
          <span className="site-nav-links">
            {links ?? (
              <>
                <a href="/#examples">Examples</a>
                <a href="/#how-it-works">How it works</a>
                <a href="/pricing">Pricing</a>
              </>
            )}
          </span>
          <a className="text-link" href="/studio">
            Sign in
          </a>
          <a className="button button-primary" href="/studio">
            Start free
          </a>
        </nav>
      </div>
    </header>
  );
}

export function MarketingChrome({
  children,
  nav,
  className,
}: {
  children: ReactNode;
  nav?: ReactNode;
  className?: string;
}) {
  return (
    <main className={`marketing-shell ${className || ""}`}>
      <SiteNav links={nav} />
      {children}
      <footer className="site-footer">
        <div className="site-footer-inner">
          <div className="site-footer-brand">
            <span className="wordmark">Orune</span>
            <p>
              Written prompts in, narrated animated lessons out. Rendered with
              Manim and Remotion, editable frame by frame.
            </p>
          </div>
          <div className="site-footer-column">
            <h2>Product</h2>
            <a href="/#examples">Examples</a>
            <a href="/#how-it-works">How it works</a>
            <a href="/pricing">Pricing</a>
            <a href="/studio">Open the studio</a>
          </div>
          <div className="site-footer-column">
            <h2>Support</h2>
            <a href="/#faq">Questions</a>
            <a href={`mailto:${CONTACT_EMAIL}`}>Contact us</a>
          </div>
          <div className="site-footer-column">
            <h2>Legal</h2>
            <a href="/privacy">Privacy</a>
            <a href="/terms">Terms</a>
          </div>
        </div>
        <div className="site-footer-base">
          <span>&copy; {new Date().getFullYear()} Orune</span>
          <span>Every lesson on this page was generated by Orune.</span>
        </div>
      </footer>
    </main>
  );
}
