#!/usr/bin/env node
/** Render one Remotion Studio project into the same stable assets as Manim. */

import { execFileSync } from "node:child_process";
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { bundle } from "@remotion/bundler";
import { renderMedia, selectComposition } from "@remotion/renderer";
import { validateGenerationRequest } from "./validate_generation_request.mjs";

function fail(message) {
  console.error(message);
  process.exit(1);
}

function run(command, args, timeout = 180_000) {
  try {
    return execFileSync(command, args, {
      encoding: "utf8",
      stdio: ["ignore", "pipe", "pipe"],
      timeout,
      maxBuffer: 8 * 1024 * 1024,
    });
  } catch (error) {
    const stderr = typeof error?.stderr === "string" ? error.stderr.slice(-4000) : "";
    fail(stderr || `${command} failed.`);
  }
}

function probeVideo(output) {
  const raw = run("ffprobe", [
    "-v", "error", "-select_streams", "v:0",
    "-show_entries", "stream=width,height,avg_frame_rate:format=duration,bit_rate",
    "-of", "json", output,
  ], 30_000);
  const data = JSON.parse(raw);
  const stream = data.streams[0];
  const [numerator, denominator] = stream.avg_frame_rate.split("/").map(Number);
  return {
    duration: Number(data.format.duration),
    width: Number(stream.width),
    height: Number(stream.height),
    fps: numerator / Math.max(denominator, 1),
    bitRate: Number(data.format.bit_rate || 0),
  };
}

async function main() {
  if (process.argv.length < 3) fail("Usage: render_remotion.mjs PROJECT_DIR [balanced] [remotion|composite]");
  const here = path.dirname(fileURLToPath(import.meta.url));
  const root = path.resolve(here, "..");
  const allowedRoot = path.resolve(root, "studio", "projects");
  const projectDir = path.resolve(process.argv[2]);
  const renderer = process.argv[4] || "remotion";
  if (!new Set(["remotion", "composite"]).has(renderer)) fail("Renderer metadata must be remotion or composite.");
  const relative = path.relative(allowedRoot, projectDir);
  if (!relative || relative.startsWith("..") || path.isAbsolute(relative)) {
    fail("Project directory must be a child of studio/projects.");
  }
  try { validateGenerationRequest(projectDir, renderer); } catch (error) { fail(error instanceof Error ? error.message : "Generation freshness check failed."); }

  const source = path.join(projectDir, "video.tsx");
  if (!fs.existsSync(source)) fail("video.tsx does not exist.");
  const code = fs.readFileSync(source, "utf8");
  for (const required of ["GeneratedVideo", "LayoutAudit", "LayoutItem", "registerRoot"]) {
    if (!code.includes(required)) fail(`video.tsx must use ${required}.`);
  }
  if ((code.match(/<LayoutAudit\b/g) || []).length !== 1) fail("video.tsx must render exactly one LayoutAudit.");
  if ((code.match(/<LayoutItem\b/g) || []).length < 1) fail("video.tsx must wrap its independent visual groups in LayoutItem.");

  const started = Date.now();
  const rawOutput = path.join(projectDir, "output.remotion.mp4");
  const output = path.join(projectDir, "output.mp4");
  fs.rmSync(rawOutput, { force: true });
  try {
    const publicDir = path.join(projectDir, "public");
    const serveUrl = await bundle({ entryPoint: source, publicDir: fs.existsSync(publicDir) ? publicDir : undefined });
    const composition = await selectComposition({ serveUrl, id: "GeneratedVideo" });
    await renderMedia({
      composition,
      serveUrl,
      codec: "h264",
      audioCodec: "aac",
      outputLocation: rawOutput,
      concurrency: "50%",
      colorSpace: "bt709",
      pixelFormat: "yuv420p",
    });
  } catch (error) {
    fail(error instanceof Error ? error.message : "Remotion render failed.");
  }
  run("ffmpeg", ["-y", "-i", rawOutput, "-c", "copy", "-movflags", "+faststart", output], 60_000);
  fs.rmSync(rawOutput, { force: true });

  const narrationConfigPath = path.join(projectDir, "narration-config.json");
  let narrationEnabled = true;
  if (fs.existsSync(narrationConfigPath)) {
    try {
      narrationEnabled = JSON.parse(fs.readFileSync(narrationConfigPath, "utf8")).enabled !== false;
    } catch {
      fail("narration-config.json must contain valid JSON.");
    }
  }

  let narration = { status: "disabled", enabled: false };
  if (narrationEnabled) {
    if (!fs.existsSync(path.join(projectDir, "narration.json"))) fail("Voice is enabled, but narration.json does not exist.");
    const result = run("node", [`--env-file-if-exists=${path.join(root, ".env")}`, path.join(root, "scripts", "generate_narration.mjs"), projectDir], 300_000);
    narration = JSON.parse(result.trim().split(/\r?\n/).at(-1));
    if (narration.status !== "ready" || narration.enabled !== true || narration.provider !== "speechify" || narration.model !== "simba-3.2") {
      fail("Narration must be generated by Speechify simba-3.2; fallback audio is not accepted.");
    }
  }

  const media = probeVideo(output);
  const posterTime = Math.min(Math.max(media.duration * 0.18, 0.5), Math.max(media.duration - 0.1, 0.5));
  const poster = path.join(projectDir, "poster.png");
  run("ffmpeg", ["-y", "-ss", posterTime.toFixed(3), "-i", output, "-frames:v", "1", poster], 60_000);
  const interval = Math.max(media.duration / 12, 0.12);
  const contactSheet = path.join(projectDir, "contact-sheet.png");
  run("ffmpeg", [
    "-y", "-i", output,
    "-vf", `fps=1/${interval.toFixed(4)},scale=360:-2,tile=4x3:padding=8:margin=8:color=white`,
    "-frames:v", "1", contactSheet,
  ], 90_000);

  const metadata = {
    scene: "GeneratedVideo",
    renderer,
    quality: process.argv[3] || "balanced",
    ...media,
    fps: Number(media.fps.toFixed(3)),
    bytes: fs.statSync(output).size,
    renderSeconds: Number(((Date.now() - started) / 1000).toFixed(2)),
    source: "video.tsx",
    output: "output.mp4",
    poster: "poster.png",
    contactSheet: "contact-sheet.png",
    narration,
  };
  fs.writeFileSync(path.join(projectDir, "metadata.json"), JSON.stringify(metadata, null, 2));
  console.log(JSON.stringify(metadata));
}

await main();
